<a href="https://colab.research.google.com/github/Bhavleenk/ai-ml-dl/blob/main/Numpy_Notebook/Numpy_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#arrays vs lists
import numpy as np

In [ ]:
L=[1,2,3]

In [ ]:
A=np.array([1,2,3])

In [ ]:
for e in L:
  print(e)

1
2
3


In [ ]:
for e in A:
  print(e)

1
2
3


In [ ]:
L.append(4)

In [ ]:
L #size of list can change but size of array cannot

[1, 2, 3, 4]

In [ ]:
L +[5]

[1, 2, 3, 4, 5]

In [ ]:
A + np.array([4]) #added 4 to each element

array([5, 6, 7])

In [ ]:
A + np.array([4,5,6])

array([5, 7, 9])

In [ ]:
2 * A

array([2, 4, 6])

In [ ]:
2 * L

[1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
L + L

[1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
L2 = []
for e in L:
  L2.append(e+3)

In [ ]:
L2

[4, 5, 6, 7]

In [ ]:
L2 = [e+3 for e in L]
L2

[4, 5, 6, 7]

In [ ]:
L**2

TypeError: ignored

In [ ]:
L2 =[]
for e in L:
  L2.append(e**2)
L2

[1, 4, 9, 16]

In [ ]:
A**2


array([1, 4, 9])

In [ ]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [ ]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [ ]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [ ]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])

In [ ]:
# DOT PRODUCT
#The zip() function combines the contents of two or more iterables. 
#zip() returns a zip object
a=np.array([1,2])
b=np.array([3,4])

In [ ]:
dot =0
for e,f in zip(a,b):
  dot+=e*f
dot

11

In [ ]:
dot=0
for i in range(len(a)):
  dot+=a[i]*b[i]
dot

11

In [ ]:
a*b


array([3, 8])

In [ ]:
np.sum(a*b)

11

In [ ]:
(a*b).sum()

11

In [ ]:
np.dot(a,b)

11

In [ ]:
a.dot(b)

11

In [ ]:
b.dot(a)

11

In [ ]:
a@b

11

In [ ]:
amag=np.sqrt((a*a).sum()) #magnitude of a

In [ ]:
amag

2.23606797749979

In [ ]:
np.linalg.norm(a) #to find magnitude

2.23606797749979

In [ ]:
cosangle=a.dot(b)/(np.linalg.norm(a)*np.linalg.norm(b))

In [ ]:
cosangle

0.9838699100999074

In [ ]:
angle=np.arccos(cosangle) #inverse of cos
angle

0.17985349979247847

In [ ]:
#Matrices
L = [[1,2],[3,4]]
L

[[1, 2], [3, 4]]

In [ ]:
L[0]

[1, 2]

In [ ]:
L[0][1]

2

In [ ]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [ ]:
A[0][1]

2

In [ ]:
A[0,1]

2

In [ ]:
A[:,0]

array([1, 3])

In [ ]:
A.T
#transpose of matrix A

array([[1, 3],
       [2, 4]])

In [ ]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [ ]:
np.exp(L)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [ ]:
B=np.array([[1,2,3],[4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
A.dot(B) #for matrix multiplication

array([[ 9, 12, 15],
       [19, 26, 33]])

In [ ]:
np.linalg.det(A) #detedrminant of matrix

-2.0000000000000004

In [ ]:
np.linalg.inv(A) #inverse of matrix

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
np.linalg.inv(A).dot(A) #to get identity

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [ ]:
np.trace(A) #trace matrix

5

In [ ]:
np.diag(A) #to get diagonal elements of matrix

array([1, 4])

In [ ]:
np.diag([1,4])

array([[1, 0],
       [0, 4]])

In [ ]:
np.linalg.eig(A) #eigen vectors

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [ ]:
Lam, V=np.linalg.eig(A)

In [ ]:
V[:,0]*Lam[0]==A@V[:,0]

array([ True, False])

In [ ]:
V[:,0]*Lam[0], A@V[:,0]

(array([ 0.30697009, -0.21062466]), array([ 0.30697009, -0.21062466]))

In [ ]:
np.allclose(V[:,0]*Lam[0],A@V[:,0]) #to check if 2 arrays are same

True

In [ ]:
np.allclose(V @ np.diag(Lam),A @ V)

True

In [ ]:
#Solving Linear Eqns
#create array
A=np.array([[1,1],[1.5,4]])
b=np.array([2200,5050])

In [ ]:
#to solve above
np.linalg.solve(A,b)
#here, we could have used a * x = b, but that is slower method the above algo 
#is easy and faster
#to a inv wala mehtod multiply a inv on both sides

array([1500.,  700.])

In [ ]:
np.linalg.inv(A).dot(b) #a*x=b method

array([1500.,  700.])

In [ ]:
# Generating Data
np.zeros((2,3)) #array of 0 of size 2*3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2,3)) #array of 1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
10 * np.ones((2,3)) #array of 10

array([[10., 10., 10.],
       [10., 10., 10.]])

In [ ]:
np.eye(3) #3*3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.random()

0.7460084463859455

In [ ]:
np.random.random((2,3)) #random matrix, histogram

array([[0.72196408, 0.04702274, 0.55886193],
       [0.49326853, 0.45986726, 0.202303  ]])

In [ ]:
np.random.randn(2,3) #normal distribution
# we get some + and some - numbers
# mean=0 and variance = 1

array([[ 0.10314426, -0.86045618,  0.92303005],
       [-1.90515676,  1.33288423,  0.21287209]])

In [ ]:
R = np.random.randn(10000)

In [ ]:
R.mean() # o/p is approx equal to 0

-0.00617642470615971

In [ ]:
np.mean(R)

-0.00617642470615971

In [ ]:
R.var() # to calculate variance, o/p is approx equal to 1

0.983419469457537

In [ ]:
R.std() #sqrt of variance

0.9916750826039429

In [ ]:
R = np.random.randn(10000,3)

In [ ]:
R.mean(axis=0) 

array([-0.00217767,  0.00166986,  0.0158302 ])

In [ ]:
R.mean(axis=1).shape

(10000,)

In [ ]:
np.cov(R) #covariance

array([[ 1.04495728, -0.672284  ,  0.06109432, ..., -0.34194864,
         0.33148506, -0.46130588],
       [-0.672284  ,  3.74671002, -5.01846888, ...,  0.67378194,
        -0.37186014,  1.01209128],
       [ 0.06109432, -5.01846888,  7.48415461, ..., -0.70174985,
         0.25765135, -1.10162936],
       ...,
       [-0.34194864,  0.67378194, -0.70174985, ...,  0.17403154,
        -0.13018944,  0.24889745],
       [ 0.33148506, -0.37186014,  0.25765135, ..., -0.13018944,
         0.11274425, -0.18056701],
       [-0.46130588,  1.01209128, -1.10162936, ...,  0.24889745,
        -0.18056701,  0.35803288]])

In [ ]:
np.cov(R).shape

(10000, 10000)

In [ ]:
np.cov(R.T) #close to identity matrix

array([[1.00911395, 0.00252568, 0.00377867],
       [0.00252568, 0.99599622, 0.01636517],
       [0.00377867, 0.01636517, 0.97907916]])

In [ ]:
np.cov(R, rowvar=False)

array([[1.00911395, 0.00252568, 0.00377867],
       [0.00252568, 0.99599622, 0.01636517],
       [0.00377867, 0.01636517, 0.97907916]])

In [ ]:
# Generate random integers
np.random.randint(0,10,size=(3,3))

array([[7, 4, 3],
       [7, 5, 3],
       [9, 5, 6]])

In [ ]:
np.random.choice(10,size=(3,3)) #function same as above

array([[4, 1, 3],
       [1, 7, 6],
       [1, 5, 6]])

In [ ]:
# NUMPY EXERCISE
